export interface Account {
  id: number;
  name: string;
  product: "Fresh QMS" | "Migrated QMS";
  startDate: string;
  validationDate: string;
  createdAt: string;
  status: "Open" | "Closed" | "Churned" | "Complete";
  journeyStatus: "On Track" | "Stuck" | "Complete";
  arr: number;
  guru: string;
  csat: number;
  churned: boolean;
  churnReason: string;
  churnNotes: string[];
  riskNotes: string[];
  csatHistory?: { month: string; score: number }[];
  isOnboarding: boolean;
  implementationType: "Standard" | "Complex" | "Enterprise" | "Quick Start";
  completedDate?: string;
  milestoneDate: string;
  phase: "Kickoff" | "Planning" | "Implementation" | "Testing" | "Go Live";
  tasksCompleted: number;
  totalTasks: number;
  tasksCompletedHours: number;
  totalTasksHours: number;
  goLiveDate?: string;
  previousWeekProgress?: number;
}

export const accounts: Account[] = [
  {
    id: 1,
    name: "Acme Corp",
    product: "Fresh QMS",
    startDate: "2025-09-01",
    validationDate: "2025-09-09",
    createdAt: "2025-09-24",
    status: "Open",
    journeyStatus: "On Track",
    arr: 12000,
    guru: "Stacey",
    csat: 4.5,
    churned: false,
    churnReason: "",
    churnNotes: [],
    riskNotes: ["Waiting client data", "Delayed validation"],
    csatHistory: [
      { month: "2025-01", score: 4.2 },
      { month: "2025-02", score: 4.3 },
      { month: "2025-03", score: 4.5 },
    ],
    isOnboarding: true,
    implementationType: "Standard",
    milestoneDate: "2025-10-15",
    phase: "Implementation",
    tasksCompleted: 45,
    totalTasks: 80,
    tasksCompletedHours: 120,
    totalTasksHours: 200,
    previousWeekProgress: 52,
    goLiveDate: "2025-11-01",
  },
  {
    id: 2,
    name: "Beta Health",
    product: "Migrated QMS",
    startDate: "2025-08-22",
    validationDate: "2025-08-30",
    createdAt: "2025-09-26",
    status: "Churned",
    journeyStatus: "Complete",
    arr: 8000,
    guru: "Ana",
    csat: 3.2,
    churned: true,
    churnReason: "Budget constraints",
    churnNotes: ["Lost budget approval", "CFO rejected renewal", "Budget constraints cited as primary reason"],
    riskNotes: ["Stopped responding", "Low engagement"],
    csatHistory: [
      { month: "2025-01", score: 3.8 },
      { month: "2025-02", score: 3.5 },
      { month: "2025-03", score: 3.2 },
    ],
    isOnboarding: false,
    implementationType: "Standard",
    milestoneDate: "2025-08-30",
    phase: "Go Live",
    tasksCompleted: 50,
    totalTasks: 50,
    tasksCompletedHours: 150,
    totalTasksHours: 150,
  },
  {
    id: 3,
    name: "TechStart Inc",
    product: "Fresh QMS",
    startDate: "2025-09-10",
    validationDate: "2025-09-15",
    createdAt: "2025-09-25",
    status: "Open",
    journeyStatus: "On Track",
    arr: 15000,
    guru: "Stacey",
    csat: 4.8,
    churned: false,
    churnReason: "",
    churnNotes: [],
    riskNotes: [],
    csatHistory: [
      { month: "2025-01", score: 4.6 },
      { month: "2025-02", score: 4.7 },
      { month: "2025-03", score: 4.8 },
    ],
    isOnboarding: true,
    implementationType: "Quick Start",
    milestoneDate: "2025-10-20",
    phase: "Planning",
    tasksCompleted: 15,
    totalTasks: 40,
    tasksCompletedHours: 30,
    totalTasksHours: 100,
    previousWeekProgress: 30,
    goLiveDate: "2025-10-25",
  },
  {
    id: 4,
    name: "Global Solutions",
    product: "Fresh QMS",
    startDate: "2025-08-15",
    validationDate: "2025-08-28",
    createdAt: "2025-09-20",
    status: "Open",
    journeyStatus: "On Track",
    arr: 25000,
    guru: "Carlos",
    csat: 4.6,
    churned: false,
    churnReason: "",
    churnNotes: [],
    riskNotes: ["Pending training session"],
    csatHistory: [
      { month: "2025-01", score: 4.4 },
      { month: "2025-02", score: 4.5 },
      { month: "2025-03", score: 4.6 },
    ],
    isOnboarding: true,
    implementationType: "Enterprise",
    milestoneDate: "2025-11-15",
    phase: "Implementation",
    tasksCompleted: 60,
    totalTasks: 120,
    tasksCompletedHours: 180,
    totalTasksHours: 350,
    previousWeekProgress: 45,
    goLiveDate: "2025-12-01",
  },
  {
    id: 5,
    name: "MediCare Plus",
    product: "Migrated QMS",
    startDate: "2025-09-05",
    validationDate: "2025-09-18",
    createdAt: "2025-09-27",
    status: "Open",
    journeyStatus: "On Track",
    arr: 18000,
    guru: "Ana",
    csat: 4.3,
    churned: false,
    churnReason: "",
    churnNotes: [],
    riskNotes: ["Awaiting data migration completion"],
    csatHistory: [
      { month: "2025-01", score: 4.1 },
      { month: "2025-02", score: 4.2 },
      { month: "2025-03", score: 4.3 },
    ],
    isOnboarding: true,
    implementationType: "Complex",
    milestoneDate: "2025-10-30",
    phase: "Implementation",
    tasksCompleted: 40,
    totalTasks: 90,
    tasksCompletedHours: 110,
    totalTasksHours: 250,
    previousWeekProgress: 40,
    goLiveDate: "2025-11-15",
  },
  {
    id: 6,
    name: "QuickPharma",
    product: "Fresh QMS",
    startDate: "2025-07-20",
    validationDate: "2025-07-25",
    createdAt: "2025-08-10",
    status: "Churned",
    journeyStatus: "Complete",
    arr: 9000,
    guru: "Stacey",
    csat: 2.8,
    churned: true,
    churnReason: "Switched to competitor",
    churnNotes: ["Competitor offered lower price", "Feature gap identified", "Switched to competitor after evaluation"],
    riskNotes: ["Multiple escalations", "Poor response time"],
    csatHistory: [
      { month: "2025-01", score: 3.5 },
      { month: "2025-02", score: 3.0 },
      { month: "2025-03", score: 2.8 },
    ],
    isOnboarding: false,
    implementationType: "Standard",
    milestoneDate: "2025-08-01",
    phase: "Go Live",
    tasksCompleted: 55,
    totalTasks: 55,
    tasksCompletedHours: 140,
    totalTasksHours: 140,
  },
  {
    id: 7,
    name: "HealthFirst",
    product: "Migrated QMS",
    startDate: "2025-09-12",
    validationDate: "2025-09-22",
    createdAt: "2025-09-28",
    status: "Complete",
    journeyStatus: "Complete",
    arr: 30000,
    guru: "Carlos",
    csat: 4.7,
    churned: false,
    churnReason: "",
    churnNotes: [],
    riskNotes: [],
    csatHistory: [
      { month: "2025-01", score: 4.5 },
      { month: "2025-02", score: 4.6 },
      { month: "2025-03", score: 4.7 },
    ],
    isOnboarding: false,
    implementationType: "Enterprise",
    completedDate: "2025-09-28",
    milestoneDate: "2025-09-28",
    phase: "Go Live",
    tasksCompleted: 120,
    totalTasks: 120,
    tasksCompletedHours: 350,
    totalTasksHours: 350,
    goLiveDate: "2025-09-28",
  },
  {
    id: 8,
    name: "BioLabs Co",
    product: "Fresh QMS",
    startDate: "2025-09-08",
    validationDate: "2025-09-14",
    createdAt: "2025-09-26",
    status: "Open",
    journeyStatus: "Stuck",
    arr: 11000,
    guru: "Stacey",
    csat: 3.5,
    churned: false,
    churnReason: "",
    churnNotes: [],
    riskNotes: ["Delayed kickoff meeting", "Low engagement from stakeholders", "Concerns about implementation timeline"],
    csatHistory: [
      { month: "2025-01", score: 4.0 },
      { month: "2025-02", score: 3.7 },
      { month: "2025-03", score: 3.5 },
    ],
    isOnboarding: true,
    implementationType: "Standard",
    milestoneDate: "2025-10-10",
    phase: "Kickoff",
    tasksCompleted: 5,
    totalTasks: 70,
    tasksCompletedHours: 12,
    totalTasksHours: 180,
    previousWeekProgress: 5,
    goLiveDate: "2025-11-05",
  },
  {
    id: 9,
    name: "SafeMed Systems",
    product: "Migrated QMS",
    startDate: "2025-06-15",
    validationDate: "2025-06-25",
    createdAt: "2025-07-01",
    status: "Churned",
    journeyStatus: "Complete",
    arr: 13000,
    guru: "Ana",
    csat: 3.0,
    churned: true,
    churnReason: "Internal restructuring",
    churnNotes: ["Company restructuring announced", "Project indefinitely postponed", "Internal restructuring led to cancellation"],
    riskNotes: ["Project put on hold", "Budget reallocated"],
    csatHistory: [
      { month: "2025-01", score: 3.8 },
      { month: "2025-02", score: 3.3 },
      { month: "2025-03", score: 3.0 },
    ],
    isOnboarding: false,
    implementationType: "Complex",
    milestoneDate: "2025-07-01",
    phase: "Planning",
    tasksCompleted: 20,
    totalTasks: 90,
    tasksCompletedHours: 45,
    totalTasksHours: 250,
  },
  {
    id: 10,
    name: "PharmaCore",
    product: "Fresh QMS",
    startDate: "2025-09-15",
    validationDate: "2025-09-25",
    createdAt: "2025-09-29",
    status: "Open",
    journeyStatus: "Stuck",
    arr: 28000,
    guru: "Carlos",
    csat: 4.9,
    churned: false,
    churnReason: "",
    churnNotes: [],
    riskNotes: ["Waiting for resource allocation", "Key stakeholder on leave"],
    csatHistory: [
      { month: "2025-01", score: 4.7 },
      { month: "2025-02", score: 4.8 },
      { month: "2025-03", score: 4.9 },
    ],
    isOnboarding: true,
    implementationType: "Enterprise",
    milestoneDate: "2025-11-30",
    phase: "Planning",
    tasksCompleted: 25,
    totalTasks: 130,
    tasksCompletedHours: 60,
    totalTasksHours: 400,
    previousWeekProgress: 18,
    goLiveDate: "2025-12-15",
  },
  {
    id: 11,
    name: "VitalCare Systems",
    product: "Fresh QMS",
    startDate: "2025-09-20",
    validationDate: "2025-09-28",
    createdAt: "2025-10-01",
    status: "Open",
    journeyStatus: "On Track",
    arr: 16000,
    guru: "Stacey",
    csat: 4.4,
    churned: false,
    churnReason: "",
    churnNotes: [],
    riskNotes: [],
    csatHistory: [
      { month: "2025-01", score: 4.2 },
      { month: "2025-02", score: 4.3 },
      { month: "2025-03", score: 4.4 },
    ],
    isOnboarding: true,
    implementationType: "Standard",
    milestoneDate: "2025-10-25",
    phase: "Kickoff",
    tasksCompleted: 8,
    totalTasks: 65,
    tasksCompletedHours: 18,
    totalTasksHours: 160,
    previousWeekProgress: 10,
    goLiveDate: "2025-11-20",
  },
  {
    id: 12,
    name: "MedFlow Technologies",
    product: "Migrated QMS",
    startDate: "2025-08-10",
    validationDate: "2025-08-20",
    createdAt: "2025-09-15",
    status: "Complete",
    journeyStatus: "Complete",
    arr: 22000,
    guru: "Ana",
    csat: 4.6,
    churned: false,
    churnReason: "",
    churnNotes: [],
    riskNotes: [],
    csatHistory: [
      { month: "2025-01", score: 4.4 },
      { month: "2025-02", score: 4.5 },
      { month: "2025-03", score: 4.6 },
    ],
    isOnboarding: false,
    implementationType: "Complex",
    completedDate: "2025-09-30",
    milestoneDate: "2025-09-30",
    phase: "Go Live",
    tasksCompleted: 95,
    totalTasks: 95,
    tasksCompletedHours: 260,
    totalTasksHours: 260,
    goLiveDate: "2025-09-30",
  },
];
